name: Code checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: pip install -r requirements.txt
      - name: Run mypy
        run: mypy main.py
      - name: Run tests
        run: pytest -v